apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-api
  template:
    metadata:
      labels:
        app: my-api
    spec:
      containers:
      - name: my-api
        image: hapolonio/k8-test-api-2:v3
        resources:
          requests:
            memory: "32Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
          - name: MONGODB_URI
            value: mongodb://mongouser:mongopwd@mongodb-service:27017/admin

---

apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: my-api
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: LoadBalancer